name: Fetch Fuel Prices Daily

on:
  schedule:
    # Runs at 12:00 UTC every day
    - cron: '0 12 * * *'
  # Allows manual trigger from GitHub Actions tab
  workflow_dispatch:

jobs:
  fetch-fuel-prices:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Supabase Edge Function
        run: |
          curl -X POST 'https://${{ secrets.SUPABASE_PROJECT_REF }}.supabase.co/functions/v1/fetch-fuel-prices' \
          -H 'Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}' \
          -H 'Content-Type: application/json' 