name: Fetch Fuel Prices Daily

on:
  # Triggers the workflow once every 24 hours after it is manually invoked or initially triggered
  workflow_dispatch:
  schedule:
    # Runs every 24 hours at the same time it was first triggered
    - cron: '0 12 * * *'  # Will trigger at midday UTC, but will repeat every 24 hours from the first invocation

jobs:
  fetch-fuel-prices:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Supabase Edge Function
        run: |
          curl -X POST 'https://${{ secrets.SUPABASE_PROJECT_REF }}.supabase.co/functions/v1/fetch-fuel-prices' \
          -H 'Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}' \
          -H 'Content-Type: application/json'
